name: Lint and Test Helm Chart

on:
  pull_request:
    paths:
      - 'deploy/helm/**'
  push:
    branches:
      - main
    paths:
      - 'deploy/helm/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main --charts deploy/helm/fluxiondb

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Run chart-testing (install)
        run: |
          ct install --target-branch main --charts deploy/helm/fluxiondb \
            --helm-extra-set-args "--set secret.secretKey=test-secret-key"

